import { createSlice, createAsyncThunk, type PayloadAction } from "@reduxjs/toolkit";
import type { RootState } from "lib/redux/store";
import type {
  Snapshot,
  HistoryConfig,
  ResumeDiff,
  SectionDiff,
} from "lib/history/types";
import { DEFAULT_HISTORY_CONFIG } from "lib/history/types";
import {
  saveSnapshot,
  saveSnapshotIdle,
  getSnapshot,
  getAllSnapshotsByResumeId,
  deleteSnapshot,
  updateSnapshotTag,
  getHistoryConfig,
  saveHistoryConfig,
  cleanupOldSnapshots,
} from "lib/history/indexedDB";
import { diffResume, hasAnyChanges } from "lib/history/diff";
import type { Resume, Settings } from "lib/redux/types";

interface HistoryState {
  snapshots: Snapshot[];
  currentSnapshotId: string | null;
  selectedSnapshotIds: [string | null, string | null];
  diff: SectionDiff[] | null;
  config: HistoryConfig;
  loading: boolean;
  error: string | null;
  isSaving: boolean;
}

const initialState: HistoryState = {
  snapshots: [],
  currentSnapshotId: null,
  selectedSnapshotIds: [null, null],
  diff: null,
  config: DEFAULT_HISTORY_CONFIG,
  loading: false,
  error: null,
  isSaving: false,
};

export const fetchSnapshots = createAsyncThunk(
  "history/fetchSnapshots",
  async (resumeId: string) => {
    return getAllSnapshotsByResumeId(resumeId);
  }
);

export const fetchConfig = createAsyncThunk(
  "history/fetchConfig",
  async (resumeId: string) => {
    return getHistoryConfig(resumeId);
  }
);

export const createSnapshot = createAsyncThunk(
  "history/createSnapshot",
  async (
    {
      resumeId,
      resume,
      settings,
      isAutoGenerated = true,
      tag = null,
    }: {
      resumeId: string;
      resume: Resume;
      settings: Settings;
      isAutoGenerated?: boolean;
      tag?: string | null;
    },
    { getState }
  ) => {
    const state = getState() as RootState;
    const config = state.history.config;

    const snapshot = await saveSnapshotIdle({
      resumeId,
      timestamp: Date.now(),
      resume,
      settings,
      tag,
      isAutoGenerated,
    });

    await cleanupOldSnapshots(resumeId, config.maxSnapshots);

    return snapshot;
  }
);

export const createSnapshotBeforeRestore = createAsyncThunk(
  "history/createSnapshotBeforeRestore",
  async ({
    resumeId,
    resume,
    settings,
  }: {
    resumeId: string;
    resume: Resume;
    settings: Settings;
  }) => {
    return saveSnapshot({
      resumeId,
      timestamp: Date.now(),
      resume,
      settings,
      tag: "before-restore",
      isAutoGenerated: false,
    });
  }
);

export const removeSnapshot = createAsyncThunk(
  "history/removeSnapshot",
  async (id: string) => {
    await deleteSnapshot(id);
    return id;
  }
);

export const setTag = createAsyncThunk(
  "history/setTag",
  async ({ id, tag }: { id: string; tag: string | null }) => {
    const snapshot = await updateSnapshotTag(id, tag);
    return snapshot;
  }
);

export const updateConfig = createAsyncThunk(
  "history/updateConfig",
  async (config: Partial<HistoryConfig> & { resumeId: string }) => {
    return saveHistoryConfig(config);
  }
);

export const computeDiff = createAsyncThunk(
  "history/computeDiff",
  async (
    { oldId, newId }: { oldId: string; newId: string },
    { getState }
  ) => {
    const state = getState() as RootState;
    const oldSnapshot = state.history.snapshots.find((s) => s.id === oldId);
    const newSnapshot = state.history.snapshots.find((s) => s.id === newId);

    if (!oldSnapshot || !newSnapshot) {
      throw new Error("Snapshot not found");
    }

    return diffResume(oldSnapshot.resume, newSnapshot.resume);
  }
);

export const historySlice = createSlice({
  name: "history",
  initialState,
  reducers: {
    selectSnapshotForDiff: (
      state,
      action: PayloadAction<{ position: 0 | 1; id: string | null }>
    ) => {
      state.selectedSnapshotIds[action.payload.position] = action.payload.id;
      state.diff = null;
    },
    clearDiff: (state) => {
      state.diff = null;
    },
    clearSnapshots: (state) => {
      state.snapshots = [];
      state.currentSnapshotId = null;
      state.selectedSnapshotIds = [null, null];
      state.diff = null;
    },
  },
  extraReducers: (builder) => {
    builder
      .addCase(fetchSnapshots.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(fetchSnapshots.fulfilled, (state, action) => {
        state.loading = false;
        state.snapshots = action.payload;
      })
      .addCase(fetchSnapshots.rejected, (state, action) => {
        state.loading = false;
        state.error = action.error.message || "Failed to fetch snapshots";
      })

      .addCase(fetchConfig.fulfilled, (state, action) => {
        state.config = action.payload;
      })

      .addCase(createSnapshot.pending, (state) => {
        state.isSaving = true;
      })
      .addCase(createSnapshot.fulfilled, (state, action) => {
        state.isSaving = false;
        state.snapshots.unshift(action.payload);
        state.currentSnapshotId = action.payload.id;
      })
      .addCase(createSnapshot.rejected, (state, action) => {
        state.isSaving = false;
        state.error = action.error.message || "Failed to create snapshot";
      })

      .addCase(createSnapshotBeforeRestore.fulfilled, (state, action) => {
        state.snapshots.unshift(action.payload);
      })

      .addCase(removeSnapshot.fulfilled, (state, action) => {
        state.snapshots = state.snapshots.filter((s) => s.id !== action.payload);
        if (state.selectedSnapshotIds[0] === action.payload) {
          state.selectedSnapshotIds[0] = null;
        }
        if (state.selectedSnapshotIds[1] === action.payload) {
          state.selectedSnapshotIds[1] = null;
        }
      })

      .addCase(setTag.fulfilled, (state, action) => {
        if (action.payload) {
          const idx = state.snapshots.findIndex((s) => s.id === action.payload!.id);
          if (idx !== -1) {
            state.snapshots[idx] = action.payload;
          }
        }
      })

      .addCase(updateConfig.fulfilled, (state, action) => {
        state.config = action.payload;
      })

      .addCase(computeDiff.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(computeDiff.fulfilled, (state, action) => {
        state.loading = false;
        state.diff = action.payload;
      })
      .addCase(computeDiff.rejected, (state, action) => {
        state.loading = false;
        state.error = action.error.message || "Failed to compute diff";
      });
  },
});

export const { selectSnapshotForDiff, clearDiff, clearSnapshots } =
  historySlice.actions;

export const selectHistory = (state: RootState) => state.history;
export const selectSnapshots = (state: RootState) => state.history.snapshots;
export const selectSelectedSnapshotIds = (state: RootState) =>
  state.history.selectedSnapshotIds;
export const selectDiff = (state: RootState) => state.history.diff;
export const selectHistoryConfig = (state: RootState) => state.history.config;
export const selectIsSavingSnapshot = (state: RootState) => state.history.isSaving;
export const selectHistoryLoading = (state: RootState) => state.history.loading;

export default historySlice.reducer;
