import { useEffect, useRef, useCallback } from "react";
import { useDispatch, useSelector } from "react-redux";
import { store, type RootState, type AppDispatch } from "lib/redux/store";
import type { Resume } from "lib/redux/types";
import type { Settings } from "lib/redux/settingsSlice";
import {
  createSnapshot,
  createSnapshotBeforeRestore,
  fetchConfig,
  fetchSnapshots,
  selectHistoryConfig,
} from "lib/history/historySlice";
import { hasAnyChanges } from "lib/history/diff";
import type { Snapshot, ResumeId } from "lib/history/types";
import { getSnapshot } from "lib/history/indexedDB";
import {
  initialResumeState,
  setResume,
  migrateResumeWithIds,
} from "lib/redux/resumeSlice";
import { initialSettings, setSettings } from "lib/redux/settingsSlice";
import { deepMerge } from "lib/deep-merge";

export const useAppDispatch: () => AppDispatch = useDispatch;
export const useAppSelector: <T>(selector: (state: RootState) => T) => T =
  useSelector;

const DEFAULT_RESUME_ID: ResumeId = "default";

export const useInitializeHistory = (resumeId: ResumeId = DEFAULT_RESUME_ID) => {
  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(fetchConfig(resumeId));
    dispatch(fetchSnapshots(resumeId));
  }, [dispatch, resumeId]);
};

export const useAutoSnapshot = (
  resumeId: ResumeId = DEFAULT_RESUME_ID,
  enabled: boolean = true
) => {
  const dispatch = useAppDispatch();
  const config = useAppSelector(selectHistoryConfig);
  const lastSavedRef = useRef<{ resume: Resume; settings: Settings } | null>(null);
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const createSnapshotIfChanged = useCallback(() => {
    const state = store.getState();
    const currentResume = state.resume;
    const currentSettings = state.settings;

    if (!lastSavedRef.current) {
      lastSavedRef.current = {
        resume: JSON.parse(JSON.stringify(currentResume)),
        settings: JSON.parse(JSON.stringify(currentSettings)),
      };
      dispatch(
        createSnapshot({
          resumeId,
          resume: currentResume,
          settings: currentSettings,
          isAutoGenerated: true,
        })
      );
      return;
    }

    const hasChanges =
      hasAnyChanges(lastSavedRef.current.resume, currentResume) ||
      JSON.stringify(lastSavedRef.current.settings) !==
        JSON.stringify(currentSettings);

    if (hasChanges) {
      lastSavedRef.current = {
        resume: JSON.parse(JSON.stringify(currentResume)),
        settings: JSON.parse(JSON.stringify(currentSettings)),
      };
      dispatch(
        createSnapshot({
          resumeId,
          resume: currentResume,
          settings: currentSettings,
          isAutoGenerated: true,
        })
      );
    }
  }, [dispatch, resumeId]);

  useEffect(() => {
    if (!enabled) return;

    const unsubscribe = store.subscribe(() => {
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
      }

      timeoutRef.current = setTimeout(
        createSnapshotIfChanged,
        config.debounceMs
      );
    });

    return () => {
      unsubscribe();
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
      }
    };
  }, [enabled, config.debounceMs, createSnapshotIfChanged]);
};

export const useRestoreSnapshot = () => {
  const dispatch = useAppDispatch();

  const restore = useCallback(
    async (
      snapshotId: string,
      resumeId: ResumeId = DEFAULT_RESUME_ID
    ): Promise<boolean> => {
      const snapshot = await getSnapshot(snapshotId);
      if (!snapshot) {
        return false;
      }

      const currentState = store.getState();

      await dispatch(
        createSnapshotBeforeRestore({
          resumeId,
          resume: currentState.resume,
          settings: currentState.settings,
        })
      ).unwrap();

      const mergedResume = deepMerge(
        initialResumeState,
        snapshot.resume
      ) as Resume;
      const mergedSettings = deepMerge(
        initialSettings,
        snapshot.settings
      ) as Settings;

      // Migrate to add stable IDs for array items
      const migratedResume = migrateResumeWithIds(mergedResume);

      dispatch(setResume(migratedResume));
      dispatch(setSettings(mergedSettings));

      return true;
    },
    [dispatch]
  );

  return restore;
};

export const useGetSnapshot = () => {
  return useCallback(async (id: string): Promise<Snapshot | undefined> => {
    return getSnapshot(id);
  }, []);
};
