import type { Resume } from "lib/redux/types";
import type { Settings } from "lib/redux/settingsSlice";

export type ResumeId = string;

export interface Snapshot {
  id: string;
  resumeId: ResumeId;
  timestamp: number;
  resume: Resume;
  settings: Settings;
  tag: string | null;
  createdAt: number;
  lastAccessedAt: number;
  isAutoGenerated: boolean;
}

export interface HistoryConfig {
  maxSnapshots: number;
  debounceMs: number;
  resumeId: ResumeId;
}

export type DiffType = "added" | "removed" | "modified" | "unchanged" | "reordered";

export interface TextDiff {
  type: DiffType;
  value: string;
  oldIndex?: number;
  newIndex?: number;
}

export interface ArrayItemDiff<T> {
  id: string;
  type: "added" | "removed" | "modified" | "unchanged" | "reordered";
  oldIndex?: number;
  newIndex?: number;
  oldValue?: T;
  newValue?: T;
  fieldDiffs?: Record<string, TextDiff[]>;
}

export interface SectionDiff {
  section: string;
  type: "text" | "array";
  diffs: TextDiff[] | ArrayItemDiff<any>[];
}

export interface ResumeDiff {
  oldSnapshotId: string;
  newSnapshotId: string;
  sections: SectionDiff[];
}

export const DEFAULT_HISTORY_CONFIG: HistoryConfig = {
  maxSnapshots: 50,
  debounceMs: 1000,
  resumeId: "default",
};

export const INDEXEDDB_DB_NAME = "openresume-history";
export const INDEXEDDB_VERSION = 1;
export const INDEXEDDB_STORE_NAME = "snapshots";
export const INDEXEDDB_CONFIG_STORE = "config";
